Repository Rodrigues-Developers/transporte-logistica, pull requests merged in 2024-04, with the labels that each got.

#71 fix: error saving the same note twice fixed
  src/app/features/registration/registration.component.ts
Labels: bug, front-end

#78 feat: group table by week date
  src/app/core/interfaces/logistic.interface.ts
  src/app/core/services/logistic.service.ts
  src/app/core/services/product.service.ts
  src/app/features/transport-detail-table/transport-detail-table.component.html
  src/app/features/transport-detail-table/transport-detail-table.component.less
  src/app/features/transport-detail-table/transport-detail-table.component.ts
Labels: enhancement, front-end

#80 Show null date
  src/app/features/transport-detail-table/transport-detail-table.component.html
  src/app/features/transport-detail-table/transport-detail-table.component.ts
Labels: bug, front-end

#83 fix: show message when the transport-detail-table is empty
  src/app/features/transport-detail-table/transport-detail-table.component.html
  src/app/features/transport-detail-table/transport-detail-table.component.less
Labels: bug, front-end

#85 Release v1.0
  src/app/features/transport-detail-table/transport-detail-table.component.html
  src/app/features/transport-detail-table/transport-detail-table.component.less
Labels: fix
